# Site settings
title: TD nextâ€¢IoT provider de la mort, working with Sigfox and Avnet Memec
email: contact@td-next.com
description: > # this means to ignore newlines until "baseurl:"
  TD next contact page. Technological provider for Internet of Things (1st Sigfox certified modules, IoT solutions...)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

host: 0.0.0.0
